### ISSUE TITLE
No player.sqlite

### ISSUE THREAD

**Issue by 3DCreeper** [CrazorTheCat/Project-BSDS#3]
Traceback (most recent call last):
  File "/home/container/Classes/MessageManager.py", line 17, in receiveMessage
    message.execute(self, message.fields)
  File "/home/container/Classes/Packets/Client/Authentification/LoginMessage.py", line 58, in execute
    db_instance = DatabaseHandler()
                  ^^^^^^^^^^^^^^^^^
  File "/home/container/Database/DatabaseHandler.py", line 8, in __init__
    self.conn = sqlite3.connect("Database/Files/player.sqlite")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

Am I doing something wrong?

**Comment by spz2020** [comment]
mkdir Database/Files
